/**
 * DevConsole Toolkit — Report Generation Agent
 * Generate formatted security reports in multiple formats.
 */

const DCTReportAgent = {
    generateJSON(findings) {
        return JSON.stringify({
            tool: 'DevConsole Toolkit',
            version: '6.1.0',
            timestamp: new Date().toISOString(),
            url: location.href,
            findings,
            summary: this.getSummary(findings)
        }, null, 2);
    },

    generateMarkdown(findings) {
        const summary = this.getSummary(findings);
        let md = `# Security Audit Report\n\n`;
        md += `**URL:** ${location.href}\n`;
        md += `**Date:** ${new Date().toISOString()}\n`;
        md += `**Tool:** DevConsole Toolkit v6.1.0\n\n`;
        md += `## Summary\n\n`;
        md += `| Metric | Count |\n|--------|-------|\n`;
        md += `| Total Findings | ${summary.total} |\n`;
        md += `| Critical | ${summary.critical} |\n`;
        md += `| High | ${summary.high} |\n`;
        md += `| Medium | ${summary.medium} |\n`;
        md += `| Low | ${summary.low} |\n\n`;
        md += `## Findings\n\n`;
        Object.entries(findings).forEach(([category, items]) => {
            if (items.length > 0) {
                md += `### ${category}\n\n`;
                items.forEach((item, i) => {
                    md += `${i + 1}. **${item.type || item.name || 'Issue'}** (${item.severity || 'medium'})\n`;
                    if (item.description) md += `   - ${item.description}\n`;
                    if (item.source) md += `   - Source: ${item.source}\n`;
                    md += '\n';
                });
            }
        });
        md += `---\n*Generated by DevConsole Toolkit v6.1.0*\n`;
        return md;
    },

    generateCSV(findings) {
        const rows = [['Category', 'Type', 'Severity', 'Source', 'Description']];
        Object.entries(findings).forEach(([category, items]) => {
            if (Array.isArray(items)) {
                items.forEach(item => {
                    rows.push([category, item.type || item.name || '', item.severity || '', item.source || '', item.description || '']);
                });
            }
        });
        return rows.map(r => r.map(c => `"${String(c).replace(/"/g, '""')}"`).join(',')).join('\n');
    },

    getSummary(findings) {
        let total = 0, critical = 0, high = 0, medium = 0, low = 0;
        Object.values(findings).forEach(items => {
            if (Array.isArray(items)) {
                items.forEach(item => {
                    total++;
                    const s = (item.severity || 'medium').toLowerCase();
                    if (s === 'critical') critical++;
                    else if (s === 'high') high++;
                    else if (s === 'medium') medium++;
                    else low++;
                });
            }
        });
        return { total, critical, high, medium, low };
    },

    download(content, filename, mimeType) {
        const blob = new Blob([content], { type: mimeType });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a'); a.href = url; a.download = filename;
        document.body.appendChild(a); a.click(); document.body.removeChild(a); URL.revokeObjectURL(url);
    },

    downloadJSON(findings) { this.download(this.generateJSON(findings), `report-${Date.now()}.json`, 'application/json'); },
    downloadMarkdown(findings) { this.download(this.generateMarkdown(findings), `report-${Date.now()}.md`, 'text/markdown'); },
    downloadCSV(findings) { this.download(this.generateCSV(findings), `report-${Date.now()}.csv`, 'text/csv'); }
};

if (typeof window !== 'undefined') window.DCTReportAgent = DCTReportAgent;
